### PR TITLE
Problem with mail program

### PR DESCRIPTION
**Pull request by voite1**
Hi, the function def select_donor(d): ---- last function in the mailroom.py has a problem.  I marked the place.  Need your help.  Please, advise.

Thanks,

Aleksey

### CODE REVIEW

**Comment by PythonCHB** [comment]
select_donor() works for me:

```
            if x[0] == n:
```

and this looks fine -- perhaps it's an issue with exact string matching. if
there is an extra space or capitalization difference, or what have you, it
won't match. I like to do somewhat fuzzy matching by doing things like:

if x[0].strip().lower() == n.strip().lower():

and you could do more if you want.

This pull request is odd -- it has ALL the commits form the main repo in it
-- but those should all be already there. I"ll try to figure out what's up,
but until then, I'm not going to merge!

Chris

## 

Christopher Barker, PhD

Python Language Consulting
- Teaching
- Scientific Software Development
- Desktop GUI and Web Development
- wxPython, numpy, scipy, Cython

**Comment by cewing** [comment]
I think the issue here is that the PR is from master on the UWPCE-PythonCert account to refactor2014 on the same account.  The pull request should be from a session branch on your personal account to the master branch of the UWPCE-PythonCert account.  

When building a pull request, you can edit the source and target by clicking the edit button at the top right in the grey bar where the two are listed.  

You should always start a pull request from your own personal account and you should work on session branches (session01, session02, etc).  You have to create these branches and commit to them yourself on your local machine, add and push them to your fork of the repository in github, and then make PRs from them to the UWPCE-PythonCert master.

**Comment by voite1** [comment]
I will send a pull request from the homework branch (i thought I did).  Can
you cancel my pull request and I will submit a new one this evening.  This
time I will make sure I use the proper branch...

On Thu, Oct 16, 2014 at 11:28 AM, Cris Ewing notifications@github.com
wrote:

> I think the issue here is that the PR is from master on the
> UWPCE-PythonCert account to refactor2014 on the same account. The pull
> request should be from a session branch on your personal account to the
> master branch of the UWPCE-PythonCert account.
> 
> When building a pull request, you can edit the source and target by
> clicking the edit button at the top right in the grey bar where the two are
> listed.
> 
> You should always start a pull request from your own personal account and
> you should work on session branches (session01, session02, etc). You have
> to create these branches and commit to them yourself on your local machine,
> add and push them to your fork of the repository in github, and then make
> PRs from them to the UWPCE-PythonCert master.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/pull/24#issuecomment-59407426
> .

## 

Aleksey Kramer
voitel@gmail.com

**Comment by cewing** [comment]
Pay close attention to the target/source information at the top of the page.  It's really quite easy to end up starting from a completely different place than you think by clicking on the wrong link.  

The pull request UI here in github still leaves a fair bit to be desired.  The best policy is to develop a habit of looking carefully before you leap.

**Comment by PythonCHB** [comment]
This got confused -- closing this one.

**Pull request closed without merging**
