### PR TITLE
Adding lightning talk material - Dave Fugelso

### PR DESCRIPTION
**Pull request by dfugelso**

### CODE REVIEW

**Comment by PythonCHB** [comment]
Wow! this has gotten rather tangled up... were you expermenting during Cris' class?

We may need to re-clone and start again -- let's see if we can clean this up before or after class this week.

**Comment by dfugelso** [comment]
Well, yea.

I'm new to Github's 'Request Pull' mechanism. Should I have just 
requested one pull even though I did a commit between pulls?

All my files look okay, btw. Did I mess up something else?

Dave

**Comment by PythonCHB** [comment]
well, a single pull request is tied to a branch. So if you make one request then, commit a change to that branch, it will automatically get added to teh pull request, if I haven't merged it yet.

But this issue here is that there is a LOT of changes all over the repo in this pull request. It looks like you were experimenting with merging in stuff from various other repos and branches.

See if you can see the whole list of changes in your pull request -- it's big!

A real git master could figure out how to clean this all up, but I suggest you may want to essentially start over -- do a new clone of the main repo, and then put your stuff back in by hand.

-Chris

**Comment by PythonCHB** [comment]
closing this -- re-submit when it's cleaned up.

**Comment by dfugelso** [comment]
Hi Chris-

I see what I did... that pull request number 5 is actually trying to 
merge gh-pages with master instead of my master with the class' master.

I did a later pull request for session 2 homework and everything is 
merged in, although commit comments are a bit messed up.

Anyway, I think I'm good.

Dave

**Comment by PythonCHB** [comment]
yup -- looks good now.

One suggestion -- avoid names with spaces in them. the tool sall work with them, but command line usage is a little uglier -- you need to escape the spaces, or use quotes.

I use underscores or "StudlyCaps" to get easy to read names without spaces.
-Chris

**Pull request closed without merging**
